/*If the service is generated automatically (with automatically i mean executing the command "ng g s services/logging") Angular will
* generate the following code:
.....
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class LoggingService {

  constructor() { }
}
.....
The code generated by Angular will work but also the code in this branch that isn't commented will work.
*/
export class LoggingService {
  logMessage(message: string) {
    console.log(`Timestamp: ${new Date()}. Message: ${message}`);
  }
}
